// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import { IFAssetsFXRP } from "./interfaces/IFAssetsFXRP.sol";

/// @title MerchantPayment
/// @notice Executes the FXRP leg of a merchant QR payment on Flare.
/// @dev This contract does not connect to or settle the regulated Indonesian QRIS rail.
///      A licensed PJP/acquirer integration is required for production IDR settlement.
contract MerchantPayment {
    struct PaymentRecord {
        address payer;
        address merchant;
        uint256 amount;
        uint256 idrQuote;
        bytes32 merchantReferenceHash;
        uint256 deadline;
        uint256 timestamp;
    }

    IFAssetsFXRP public immutable fxrp;

    mapping(bytes32 paymentId => PaymentRecord) private payments;
    uint256 public totalPayments;
    uint256 public totalVolume;
    bool private locked;

    event MerchantPaid(
        bytes32 indexed paymentId,
        address indexed payer,
        address indexed merchant,
        uint256 amount,
        uint256 idrQuote,
        bytes32 merchantReferenceHash,
        uint256 deadline,
        uint256 timestamp
    );

    error ZeroToken();
    error ZeroPaymentId();
    error DuplicatePaymentId(bytes32 paymentId);
    error ZeroMerchant();
    error SelfPayment();
    error ZeroAmount();
    error QuoteExpired(uint256 deadline, uint256 currentTimestamp);
    error InsufficientBalance(uint256 available, uint256 required);
    error InsufficientAllowance(uint256 allowance, uint256 required);
    error TransferFailed();
    error ReentrantCall();

    constructor(address fxrpAddress) {
        if (fxrpAddress == address(0)) revert ZeroToken();
        fxrp = IFAssetsFXRP(fxrpAddress);
    }

    /// @notice Pays a merchant in FXRP from a signed QR payment request.
    /// @param paymentId Unique identifier generated by FlareIt for idempotency.
    /// @param merchant Merchant EVM address that receives FXRP directly.
    /// @param amount FXRP amount in 6-decimal smallest units.
    /// @param idrQuote Informational IDR quote at payment creation time.
    /// @param merchantReferenceHash Hash of the merchant/PJP reference; never store raw identifiers.
    function payMerchant(
        bytes32 paymentId,
        address merchant,
        uint256 amount,
        uint256 idrQuote,
        bytes32 merchantReferenceHash,
        uint256 deadline
    ) external {
        if (locked) revert ReentrantCall();
        if (paymentId == bytes32(0)) revert ZeroPaymentId();
        if (payments[paymentId].payer != address(0)) revert DuplicatePaymentId(paymentId);
        if (merchant == address(0)) revert ZeroMerchant();
        if (merchant == msg.sender) revert SelfPayment();
        if (amount == 0) revert ZeroAmount();
        if (deadline < block.timestamp) revert QuoteExpired(deadline, block.timestamp);

        uint256 balance = fxrp.balanceOf(msg.sender);
        if (balance < amount) revert InsufficientBalance(balance, amount);

        uint256 allowed = fxrp.allowance(msg.sender, address(this));
        if (allowed < amount) revert InsufficientAllowance(allowed, amount);

        locked = true;
        payments[paymentId] = PaymentRecord({
            payer: msg.sender,
            merchant: merchant,
            amount: amount,
            idrQuote: idrQuote,
            merchantReferenceHash: merchantReferenceHash,
            deadline: deadline,
            timestamp: block.timestamp
        });

        bool success = fxrp.transferFrom(msg.sender, merchant, amount);
        if (!success) revert TransferFailed();

        unchecked {
            totalPayments += 1;
            totalVolume += amount;
        }
        locked = false;

        emit MerchantPaid(
            paymentId,
            msg.sender,
            merchant,
            amount,
            idrQuote,
            merchantReferenceHash,
            deadline,
            block.timestamp
        );
    }

    function getPayment(bytes32 paymentId) external view returns (PaymentRecord memory) {
        return payments[paymentId];
    }
}
